version: '3'

services:
  es-impulse:
     ports:
       # Make accessible by host machine
       - "9200:9200"
       - "9300:9300"
     container_name: impulse-elasticsearch
     image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
     volumes:
      # chmod 777 the es_data directory so ES can write
       - ./data/es:/usr/share/elasticsearch/data
     environment:
       - cluster.name=impulse
       - cluster.routing.allocation.disk.threshold_enabled=false
       - http.host=0.0.0.0
       - transport.host=127.0.0.1
       - xpack.security.enabled=false
     ulimits:
       nproc: 65535
       memlock:
        soft: -1
        hard: -1
     cap_add:
       - ALL
     privileged: true
