version: '3'

services:
  mongodb:
    ports:
      - "27017:27017"
    image: mongo:3.4.1
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongodb:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    restart: always
